/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HydrogenCreditsInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "balances" | "creditUser" | "getBalance" | "registerUser" | "registeredUsers" | "transferTokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TokensTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'balances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'creditUser', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registeredUsers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferTokens', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferTokens', data: BytesLike): Result;
  }

  
    export namespace TokensTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HydrogenCredits extends BaseContract {
    
    connect(runner?: ContractRunner | null): HydrogenCredits;
    waitForDeployment(): Promise<this>;

    interface: HydrogenCreditsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    creditUser: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    registerUser: TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registeredUsers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    transferTokens: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creditUser'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerUser'): TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registeredUsers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferTokens'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'TokensTransferred'): TypedContractEvent<TokensTransferredEvent.InputTuple, TokensTransferredEvent.OutputTuple, TokensTransferredEvent.OutputObject>;

    filters: {
      
      'TokensTransferred(address,address,uint256)': TypedContractEvent<TokensTransferredEvent.InputTuple, TokensTransferredEvent.OutputTuple, TokensTransferredEvent.OutputObject>;
      TokensTransferred: TypedContractEvent<TokensTransferredEvent.InputTuple, TokensTransferredEvent.OutputTuple, TokensTransferredEvent.OutputObject>;
    
    };
  }